### PR TITLE
Replace non-standard calls to getarg and system in grid_rotate

### PR DESCRIPTION
**Pull request by mgduda**
This merge replaces non-standard `getarg` and `system` calls in the grid_rotate program
with calls to the F2003 `get_command_argument` and F2008 `execute_command_line`
subroutines, respectively.

### CODE REVIEW

**Review by MiCurry — APPROVED** [review]

**Comment by mgduda** [comment]
@MiCurry As mentioned in PR #410, we could add another commit to this PR to replace the nonstandard `system` calls with `execute_command_line` calls as part of a broader objective of replacing non-standard calls of all sorts (`getarg`, `system`). What do you think?

**Comment by MiCurry** [comment]
@mgduda I think using this PR to remove `system` would be great! Two birds with one stone!

**Comment by mgduda** [comment]
@MiCurry I've just added another commit to address the `system` calls, and I've updated the PR description, too.

**Review by MiCurry — APPROVED** [review]
Looks great! Ship-it! :shipit:

**Pull request merged**
