### PR TITLE
Add python mask creator

### LINKED ISSUE #321: Improve the MPAS mask creator
The mask creator is not serving our needs very well.  It has the following issues (please add if you have others):
* It is slow, and becomes significantly more so the more complex the geojson geometry even for low resolution MPAS meshes
* It is serial, so it wastes most processors on a node
* It is written in C++, which few in the group can modify and even fewer wish to get their hands dirty with
* It produces masks on edges and vertices even when we only need masks on cells (e.g. for culling)

Some of these issues might be partially addressed by combining geojson features into a single feature before calling the mask creator when this is appropriate (e.g. only the mask from all features combined is needed).

However, a more general solution is needed.

### PR DESCRIPTION
**Pull request by xylar**
This merge adds 4 functions and corresponding command-line tools for making MPAS region, transect and flood-fill masks and for making lon/lat regions masks:
* `compute_mpas_region_masks`
* `compute_mpas_transect_masks`
* `compute_mpas_flood_fill_mask`
* `compute_lon_lat_region_masks`

The command-line tools will be used by compass as part of generating meshes and by MPAS-Analysis for generating region and transect masks efficiently for large meshes.

closes #321

### CODE REVIEW

**Comment by xylar** [comment]
## Testing

The new masking tools have been tested in both compass and MPAS-Analysis on several machines as detailed below.

### compass

The branch https://github.com/xylar/compass/tree/add_python_masks makes use of the new command-line tools for both culling global ocean meshes in `mesh` test cases and generating regions masks in `files_for_e3sm` test cases.  The results show show substantially better performance than has been seen with `mpas_tools.mesh.conversion.mask` (which uses `MpasMaskCreator.x`), particularly on larger meshes.

Machines and configurations tests:
* Anvil: `QU240`, `QUwISC240`, `EC30to60`, `ECwISC30to60`
* Chrysalis: `QU240`, `QUwISC240`
* Cori: `QU240`, `QUwISC240`
* Grizzly: `QU240`, `QUwISC240`
* Badger: `QU240`, `QUwISC240`
* Ubuntu: `QU240`, `QUwISC240`

### MPAS-Analysis

The branch https://github.com/xylar/MPAS-Analysis/tree/use_mpas_tools_python_masks changes MPAS-Analysis to use the new command-line tools to generate regions masks if they aren't already cached for a given mesh.  This approach has been tested on several machines:

* Anvil: `QU240wLI`, `QU480`
* Chrysalis: `QU240wLI`, `QU480`, `WC14to60E2r3`
* Cori: `QU480`
* Compy: `QU480`

**Comment by xylar** [comment]
@dengwirda, I wanted to make you aware of this work in case it is of use to you.  This work replaces nearly every use of `MpasMaskCreator.x` or `mpas_tools.mesh.conversion.mask()` in my workflows.  The only remaining use of `mpas_tools.mesh.conversion.mask()` is for creating transport transect masks because the python tool doesn't (yet) produce the edge sign.

I believe you have your own tools for mask creation.  It would be great to converge on a set of interoperable tools for masking if possible.  But this functionality is needed in compass and MPAS-Analysis urgently enough that I would like to go ahead with what I have for now.

**Comment by dengwirda** [comment]
@xylar, great that there's work happening re: the mask creator --- lots of opportunities to improve efficiency I think.

I'm happy to try to merge in various things from the ICoM workflow, I make use of a [fast in-polygon routine](https://github.com/dengwirda/inpoly) + sparse-matrix treatments of various MPAS operators to improve algorithmic scaling. The ICoM workflows require keeping track of various additional constraints + non-ocean parts of the mesh, etc though, which may require some thought.

**Comment by milenaveneziani** [comment]
Hi @xylar: I've been using the MpasMaskcreator tool a ton recently, for creating ocean subbasins and new transects for the WC campaign. I would like to test these new tools: should I just call the new functions with a `--help` flag to see how to run them? 
Thanks for creating these.

**Comment by xylar** [comment]
@milenaveneziani, I always try to keep the documentation up-to-date:
http://mpas-dev.github.io/MPAS-Tools/stable/mesh_conversion.html#mask-creation-with-python-multiprocessing
Please let me know if the documentation needs work, though (or submit a PR of your own).

**Comment by milenaveneziani** [comment]
Fantastic. Thanks!

**Comment by xylar** [comment]
@dengwirda, `inpoly` looks really promising!  I'll have to take a more careful look.  It runs in serial, I assume?  If it's fast, I suppose that doesn't matter.

**Pull request merged**
