### PR TITLE
Add a general script for plotting 2D output

### PR DESCRIPTION
**Pull request by trhille**
Add a generalized script for plotting 2D output for arbitrary numbers of output files, variables, and time levels.
The purposes of this script are:
1. to serve as a quick-view tool so that we don't have to `scp` large output files for simple visualization.
2. to serve as a template for more customized plotting scripts for presentations and publications.

### CODE REVIEW

**Comment by trhille** [comment]
Usage example:
```
python plot_maps.py -r /global/cscratch1/sd/trhille/Thwaites_1to8km_r02_20220427/climatology/uncoupled/remove_shear_zone/VM250/output_2015.nc,/global/cscratch1/sd/trhille/Thwaites_1to8km_r02_20220427/climatology/coupled/remove_shear_zone/VM250_enhancement_factor/output_2015.nc -t 0,-1 -v thickness,surfaceSpeed -c Blues,plasma
```
image

**Comment by trhille** [comment]
This is also flexible enough to plot results from different meshes with a single command:
```
python plot_maps.py -r /global/cscratch1/sd/trhille/Thwaites_1to8km_r02_20220427/climatology/uncoupled/remove_shear_zone/VM250/output_2015.nc,/global/cscratch1/sd/trhille/Humboldt_1to10km_r04_20210615/m5/HadGEM2/VM160_shelfMelt20myr/output.nc -t 0,-1 -v thickness,surfaceSpeed -c Blues,plasma
```
image

**Comment by trhille** [comment]
Updated usage example with new standardized color ranges and log-scale option for `surfaceSpeed`:
```
python plot_maps.py -r /global/cscratch1/sd/trhille/Thwaites_1to8km_r02_20220427/climatology/uncoupled/remove_shear_zone/VM250/output_2015.nc,/global/cscratch1/sd/trhille/Humboldt_1to10km_r04_20210615/m5/HadGEM2/VM160_shelfMelt20myr/output.nc -t 0,40,-1 -v thickness,surfaceSpeed,bedTopography -c Blues,plasma,BrBG -l False,True,False
```
image

**Comment by trhille** [comment]
@hollyhan, I just wanted to make you aware of this new tool for plotting MALI output.

**Comment by hollyhan** [comment]
> @hollyhan, I just wanted to make you aware of this new tool for plotting MALI output.

Thanks a lot @trhille ! This is extremely useful!!

**Review by matthewhoffman — CHANGES_REQUESTED** [review]
@trhille , this looks super useful and is probably long overdue!

I looked it over carefully, and I don't have any major comments.  It's clear what is happening, and the coding is concise and pythonic.

My main request is to add a description to the docstring at the top, including an explanation that files are plotted per figure, time levels per column, and variables per row. Also have the docstring describe the 3 contour lines that get added. (I think it's ok not to include in a legend.)

Other than that two optional suggestions:
* If you'd like, you could hardcode specific colormaps for the most common variables.  The colormaps argument could still override those, but we might rarely bother if the standard choices are sensible.  
* OptionParser is deprecated and we should start using ArgParser for new scripts.  Having said that, I used OptionParser in a handful of scripts in that other PR you are reviewing, so I'm going to stop short of asking you to change it here. :)

**Comment by trhille** [comment]
@matthewhoffman, thanks for those helpful suggestions. I implemented all three of them. The choices for colormaps are currently either to define colormaps for all variables or to use the default colormaps added in https://github.com/MPAS-Dev/MPAS-Tools/pull/481/commits/50c4b7a75b34dc09a5d81060ddc8eafce29ff281. I thought about being able to mix and match, but that would lead to clunky syntax like `-c Blues,default,plasma` when executing, so I decided to go with one or the other. Let me know if you think we should go with the other option.

**Review by matthewhoffman — APPROVED** [review]
@trhille , thanks for the revisions to this.  It will be very useful.

**Pull request merged**
