### PR TITLE
Add sea-ice partition tools to conda package

### PR DESCRIPTION
**Pull request by xylar**
This merge adds the following sea-ice partition tools to the `mpas_tools` conda package:
- `prepare_seaice_partitions.py`
- `create_seaice_partitions.py`
- `fix_regrid_output.exe`

It includes a small amount of clean-up of the python scripts to:
* add shebangs and make the scripts executable
* fix a typo
* remove deprecated `string.atoi()` call
* drop python 2.7 support in the form of `print_function` import (because new syntax is added that is not python 2.7 compatible)
* handle finding the `fix_regrid_output.exe` executable in the system path (e.g. from conda package)

Support for a CMake build of `fix_regrid_output.exe` has been added, as this is much easier to handle in the conda package than the existing Makefile.

The conda package has been updated to include `gfortran` and `netcdf-fortran`, needed to build `fix_regrid_output.exe`.

### CODE REVIEW

**Comment by xylar** [comment]
@akturner, I think this will make these tools a bit easier for E3SM Infrastructure folks to use for making sea-ice partition files. It is also a necessary first step in using these tools in compass.

I will make a companion PR into compass that adds support for these tools there.  I won't merge this PR until I have fully tested the other.

**Comment by xylar** [comment]
Needs considerably more work, I now see.

**Comment by xylar** [comment]
@akturner, please ignore this and focus on #484 for now.

**Review by akturner — APPROVED** [review]

**Comment by xylar** [comment]
@akturner, I rebased this onto `master` after merging #484.  That might make these changes easier to follow, in case you're interested.  Either way, I plan to merge once CI has completed.

Thanks for reviewing!

**Pull request merged**
