### PR TITLE
Land ice mesh tools to python 3

### PR DESCRIPTION
**Pull request by xylar**
Make a few minor formatting changes to the land ice mesh tools so they work in python 3 as well as python 2.

I also include `mark_horns_for_culling.py` because I think this script might be used primarily by the land-ice model and because I'm pretty sure that @matthewhoffman is the author of all 5 scripts.

### CODE REVIEW

**Comment by xylar** [comment]
@matthewhoffman, here are changes needed to make the land ice mesh tools compatible with python 3.  This should give you a sense of some of the more basic changes that are typically required.  Mostly about print formatting.

A few of the formatting changes aren't  strictly necessary but there's a strong preference for the `.format()` as opposed to ` % ` or ` + ` and I was having to alter print statements all over in any case.  If you feel strongly about those changes, I can obviously revert them.

**Comment by xylar** [comment]
I don't have a great way to test these.  I made sure they pass the `--help` test and that's about it.

**Comment by xylar** [comment]
The intention is to revise these scripts before including them in the `mpas_mesh_tools` conda package (#248)

**Comment by matthewhoffman** [comment]
@xylar , thanks for putting this together - it looks like a lot of tedious work.  I'll take a look and try the new versions out.

**Comment by xylar** [comment]
@matthewhoffman, eh, not as much work as I was anticipating.  I'm starting to learn that a lot of the difficulties between python 2 and 3 come when you use fancier features like dictionaries and parse config files and stuff like that that you really only do when putting packages together, not scripts.  With scripts, it's almost entirely the print statements.

**Comment by xylar** [comment]
Let me know if I should split `mark_horns_for_culling.py` into a separate PR.

**Comment by xylar** [comment]
@matthewhoffman, could you suggest a process I could use to test these myself?  I would like to include them in #248, which I think @mark-petersen and I will work on getting merged this week.

**Comment by mark-petersen** [comment]
My two cents: Let's take the leap on these and clean up any loose ends afterwards. @xylar has taken all reasonable precautions to change over to python 3.

**Comment by matthewhoffman** [comment]
@xylar , that sounds entirely reasonable to me.  I apologize for my failing to give this the attention it deserves.

**Comment by xylar** [comment]
Thanks @matthewhoffman.

**Pull request merged**
