### PR TITLE
Add Travis CI to test conda package and build docs

### PR DESCRIPTION
**Pull request by xylar**
The approach is similar to MPAS-Analysis but builds the conda package similarly to conda-forge.

### CODE REVIEW

**Comment by xylar** [comment]
@matthewhoffman, you are the only other frequent contributor to MPAS-Tools within the past 3 years according to my look at the [contributors page](https://github.com/MPAS-Dev/MPAS-Tools/graphs/contributors?from=2017-01-02&to=2020-03-11&type=c).  Do you have any objection to me adding Travis CI to build documentation and test the conda package?

As occasional contributors to MPAS-Tools, @mgduda, @mark-petersen and @pwolfram, you are welcome to weigh in, too, but I won't wait for your responses if I don't hear anything by the end of the day.

**Comment by pwolfram** [comment]
@xylar, I'm in favor of Travis CI being added for documentation / testing.

**Comment by mark-petersen** [comment]
Yes, sounds great!

**Comment by xylar** [comment]
@matthewhoffman, when you get a chance, can I get a "yes", "no" or "I need more time"?

**Comment by xylar** [comment]
Okay, having heard no further feedback, I'm going to go ahead with this.

**Comment by matthewhoffman** [comment]
@xylar , sorry I missed the email notifications on this until now.  This sounds good to me, but I only vaguely understand what travis will do.  I'll do a little background reading and let you know if I have any questions about it.  Thanks for this!

**Pull request merged**
