### PR TITLE
Update to v0.0.6

### PR DESCRIPTION
**Pull request by xylar**
Prepare for new release

### CODE REVIEW

**Comment by xylar** [comment]
@matthewhoffman, do you have any new tools that need hooks into the conda package before I create this new release?

**Comment by xylar** [comment]
@matthewhoffman, specifically, is the new script `add_no_water_flux_around_boundary.py` used in COMPASS?

**Comment by matthewhoffman** [comment]
@xylar , thanks for checking.  Eventually that script might get used in COMPASS, but not the foreseeable future, so let's not worry about it for now.  Go ahead and create the release when you're ready.

**Comment by xylar** [comment]
I successfully ran a local linux, python 3.7 build of the mpas_tools conda package.  I'm going to go ahead with the release.

**Pull request merged**
