### PR TITLE
Fix invalid vertices in vertex transect masks

### LINKED ISSUE #413: Error on vertex mask when creating transect masks with new tool
I started using `compute_mpas_region_masks` and `compute_mpas_transect_masks` today, with my most recent mpas-analysis conda environment on anvil, and while the region_mask tool seems to work fine, I get the following error when running the transect_masks tool:
```
  Computing vertex masks:
Traceback (most recent call last):
  File "/home/ac.milena/.conda/envs/mpas-analysis/bin/compute_mpas_transect_masks", line 11, in <module>
    sys.exit(entry_point_compute_mpas_transect_masks())
  File "/home/ac.milena/.conda/envs/mpas-analysis/lib/python3.8/site-packages/mpas_tools/mesh/mask.py", line 370, in entry_point_compute_mpas_transect_masks
    dsMasks = compute_mpas_transect_masks(
  File "/home/ac.milena/.conda/envs/mpas-analysis/lib/python3.8/site-packages/mpas_tools/mesh/mask.py", line 258, in compute_mpas_transect_masks
    _get_polygons(dsMesh, maskType)
  File "/home/ac.milena/.conda/envs/mpas-analysis/lib/python3.8/site-packages/mpas_tools/mesh/mask.py", line 1071, in _get_polygons
    assert numpy.all(vertexIndices >= 0)
AssertionError
```

I am not sure if this has something to do with my geojson file or something else.
Here is the full command I issued:
`compute_mpas_transect_masks -m EC30to60E2r2mesh -g arcticSections20210323.geojson -o EC30to60E2r2_arcticSections.20210323_newtool.nc -s 10e3 --add_edge_sign`
in this directory: `/lcrc/group/e3sm/ac.milena/mpas-region_masks`.

Note that the cell and edge masks completed without error, it only stopped at the vertex mask calculation.

### PR DESCRIPTION
**Pull request by xylar**
With this fix, the first valid vertex is copied into any invalid vertices in the triangles around vertices.  Each vertex corresponds to a polygon, but some polygons are degenerate and presumably don't intersect the transect.

closes #413

### CODE REVIEW

**Comment by xylar** [comment]
@milenaveneziani, you're going to have a hard time testing this.  It seemed like it worked for me.  But I need to make you a conda environment with a test build of this package to test with.

**Comment by xylar** [comment]
I'm having trouble building the conda package tonight.  I'll try again tomorrow.

**Comment by xylar** [comment]
@milenaveneziani, you should now be able to test (just `mpas_tools`) with:
```
source /lcrc/soft/climate/e3sm-unified/base/etc/profile.d/conda.sh
conda activate test_mpas_tools_0.5.2
```

Please let me know if this works for you and the vertex masks look okay.  BTW, what do you use vertex transect masks for anyway?

**Review by milenaveneziani — APPROVED** [review]
This worked for me @xylar, thanks. And thanks for making the testing conda environment.

**Comment by milenaveneziani** [comment]
> BTW, what do you use vertex transect masks for anyway?

I don't use them for now. I just thought it would be a good idea to make a note of the issue. I am glad this was a quick fix.

**Comment by xylar** [comment]
Thanks for testing!

**Pull request merged**
