### PR TITLE
Create a conda recipe for the mesh conversion tools

### PR DESCRIPTION
**Pull request by xylar**
This will allow them to be installed as a conda package on any HPC machine (or at least most of them) without having to worry about installing the legacy NetCDF c++ library they depend on or building them from source.

This requires:
* bundling the legacy NetCDF C++ code with the mesh conversion tools
* modifying the Makefile to allow externally defined `CC` and `CFLAGS` environment variables
* removing libnetcdf-c++ from the build and instead pointing to the local cpp and header files.

A similar approach was taken by the [tempest-remap](https://github.com/ClimateGlobalChange/tempestremap) software.

### CODE REVIEW

**Comment by xylar** [comment]
@jhkennedy, I'm hoping you can do review of the conda recipe and my inclusion of legacy NetCDF C++, since you've been looking at something similar in your tempest-remap work.  I don't necessarily need you to build the recipe, since I already made the package locally and uploaded it to my anaconda channel.  You could try the following script to test this out:
```bash
#!/bin/bash

conda create -y -n mpas_mesh_tools -c xylar   mpas_mesh_conversion_tools
conda activate mpas_mesh_tools
wget https://github.com/xylar/MPAS-Tools/raw/mesh_conversion_tools_conda_recipe/mesh_tools/mesh_conversion_tools/test/Arctic_Ocean.geojson
wget https://github.com/xylar/MPAS-Tools/raw/mesh_conversion_tools_conda_recipe/mesh_tools/mesh_conversion_tools/test/doubly_periodic_5km_100x20km_planar.160926.nc
wget https://github.com/xylar/MPAS-Tools/raw/mesh_conversion_tools_conda_recipe/mesh_tools/mesh_conversion_tools/test/ocean.nc
MpasMeshConverter.x doubly_periodic_5km_100x20km_planar.160926.nc mesh.nc
MpasCellCuller.x ocean.nc
MpasMaskCreator.x ocean.nc arctic_mask.nc -f Arctic_Ocean.geojson
```
You should see no errors and the output should look something like:
```
$ ls
arctic_mask.nc        culled_mesh.nc                                 mesh.nc
Arctic_Ocean.geojson  doubly_periodic_5km_100x20km_planar.160926.nc  ocean.nc
culled_graph.info     graph.info
```

If you do want to test the build, you'll have to modify `meta.yaml` to point to my fork instead of `MPAS-Dev` and this branch instead of `master`.  The recipe is written to work after this PR gets merged (what a pain!).

**Comment by xylar** [comment]
@mgduda, @matthewhoffman, @mark-petersen and @akturner, I'm including you to make sure you're okay with the changes I'm making to the `Makefile` for these tools and with local inclusion of the legacy NetCDF C++ code.

If you want to test out this package on an HPC or linux machine (I don't have an easy way to build an OSX version at the moment), you can follow these instructions for setting up a new conda environment (assuming you have a base environment to work from):
```
conda create -y -n mpas_mesh_tools -c xylar   mpas_mesh_conversion_tools
conda activate mpas_mesh_tools
```
You should then find `MpasMeshConverter.x`, etc. in your path.  I would very much like to know if this works for you.  If so, I can include this package as part of a broader package that can be used to setup and run COMPASS test cases without the user needing to build and point to local copies of these tools.

**Comment by xylar** [comment]
@akturner reports an issue where `cc` is being used for the default build, whereas `g++` was expected.  I'll see what I can figure out.

**Comment by xylar** [comment]
@akturner, the problem seems to be related to GNU make's implicit definition of CC:
https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

The correct compiler would be CXX, not CC and that defaults to g++, so I'm just going to make that change.

**Comment by xylar** [comment]
Thanks, @mark-petersen!

**Comment by mark-petersen** [comment]
Let's see if we can reduce file size.  Try this one for doubly periodic:
`/usr/projects/regionalclimate/COMMON_MPAS/ocean/grids/mesh_database`
`doubly_periodic_16km_64x64km_planar.160120.nc`
is 29k, with 24 cells.

**Comment by mark-petersen** [comment]
Here are small files for the global test.
<details>

```
gr1336:init_step1$ pwd
/lustre/scratch4/turquoise/mpeterse/runs/nightly_ocean_model_test_mesh_conversion_tools_conda_recipe/ocean/global_ocean_V1/QU240/performance_test/init_step1
gr1336:init_step1$ ls -lh base_mesh.nc land_mask_final.nc
lrwxrwxrwx 1 mpeterse mpeterse  92 Feb 25 12:12 base_mesh.nc -> /usr/projects/regionalclimate/COMMON_MPAS/ocean/grids/mesh_database/mesh.QU.1920km.151026.nc
-rw-r--r-- 1 mpeterse mpeterse 12K Feb 25 12:13 land_mask_final.nc
gr1336:init_step1$ ./MpasCellCuller.x base_mesh.nc culled_mesh.nc -m land_mask_final.nc


************************************************************
MPAS_CELL_CULLER:
  C++ version
  Remove cells/edges/vertices from a NetCDF MPAS Mesh file.


  Compiled on Feb 25 2019 at 11:33:46.
************************************************************


Reading input grid.
Read dimensions:
    nCells = 162
    nVertices = 320
    nEdges = 480
    vertexDegree = 3
    maxEdges = 6
    Spherical? = 1
    Periodic? = 0
Reading in mask information.
Marking cells for removal.
Removing 54 cells.
Marking vertices for removal.
Removing 48 vertices.
Marking edges for removal.
Removing 99 edges.
Writing grid dimensions
Writing grid attributes
Writing grid coordinates
Mapping and writing cell fields and culled_graph.info
Mapping and writing edge fields
Mapping and writing vertex fields
Outputting cell map
```
</details>

Then you only need these two files:
```
175K  mesh.QU.1920km.151026.nc
/usr/projects/regionalclimate/COMMON_MPAS/ocean/grids/mesh_database/mesh.QU.1920km.151026.nc
12K land_mask_final.nc
/lustre/scratch4/turquoise/mpeterse/runs/nightly_ocean_model_test_mesh_conversion_tools_conda_recipe/ocean/global_ocean_V1/QU240/performance_test/init_step1/land_mask_final.nc
```
Then you can run the command 
```
./MpasCellCuller.x base_mesh.nc culled_mesh.nc -m land_mask_final.nc
```
and it culls 54 cells. I made that land_mask_final.nc in an init_step1 just now.  If permissions are bad, use `take mpeterse` on IC and you will get it.

**Comment by mark-petersen** [comment]
Xylar, I'm happy for you to go ahead and merge in after you reduce file sizes and squash commits, so 2MB files are no longer in the history.

**Comment by xylar** [comment]
@mark-petersen, I'm happy to reduce the file sizes here.  Definitely no need for bigger files.  Just for comparison, the MPAS-Analysis repo has 8 MB of files for testing, and that's never been a problem.  e3sm_diags is 1.2 GB in size because of large files in its commit history.  It's a bit unwieldy but even that wasn't terribly unmanageable.  So I think 2 MB of binary files is not an issue if they're really needed, as long as they're not constantly changing.

**Comment by xylar** [comment]
@mark-petersen, your concern about file size should now be addressed.  I have removed the 2 2MB files from the commit history.

**Comment by xylar** [comment]
Assuming this PR gets approved, I'm going to broaden this out a bit and include a few more MPAS mesh tools to make an `mpas_mesh_tools` conda package.

I have a prototype that can be installed like this:
```
conda create -n mpas_mesh_tools -c xylar python=3.7 mpas_mesh_tools
conda activate mpas_mesh_tools
```
(You could use python 2.7 if you prefer).  You can then access any of the following:
```
MpasCellCuller.x
MpasMaskCreator.x
MpasMeshConverter.x
planar_hex
mark_horns_for_culling.py
create_landice_grid_from_generic_MPAS_grid.py
define_cullMask.py
interpolate_to_mpasli_grid.py
mark_domain_boundaries_dirichlet.py
```

**Comment by xylar** [comment]
@akturner, thanks so much for testing again!

**Comment by xylar** [comment]
Thanks @mgduda!

**Comment by xylar** [comment]
@matthewhoffman, this seems to be the lowest hanging fruit in terms of the many pull requests I currently have on MPAS-Tools.  Could you just make sure the mesh conversion tools still build for you in whichever location(s) you typically use them?

**Comment by xylar** [comment]
Thanks, @matthewhoffman.  I appreciate that your goal was to keep the tools in this repo as clean an simple to use as possible.  I'll definitely keep that goal in mind in my future additions.

**Pull request merged**
