### PR TITLE
Modifications to acme namelist file generator

### PR DESCRIPTION
**Pull request by akturner**
Renamed from acme to e3sm
Made print statements compatible with python 2 and 3
Fixed indent formatting

### CODE REVIEW

**Comment by xylar** [comment]
@jonbob and @akturner, could we get this tested and merged?

**Comment by jonbob** [comment]
@xylar and @akturner - I'm testing this but ran into a situation where the old version was more useful. Specifically I had a file I was trying to parse that had some unacceptable characters in it. This new version rejected it with the following message:
```
usage: generate_e3sm_namelist_files.py [-h] -r FILE [-d FILE]
generate_e3sm_namelist_files.py: error: inReg.xml does not exist or is not parsable. Exiting.
```
The old version was able to point out where the file was bad:
```
Traceback (most recent call last):
  File "/home/ac.jwolfe/tools/crap.py", line 284, in <module>
    registry_tree = ET.parse(args.registry)
  File "/soft/bebop/python/intel-17.0.4/2.7.13/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/soft/bebop/python/intel-17.0.4/2.7.13/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/soft/bebop/python/intel-17.0.4/2.7.13/lib/python2.7/xml/etree/ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "/soft/bebop/python/intel-17.0.4/2.7.13/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 13016, column 87
```
Is it possible to make the new one provide the same kind of traceback?

**Comment by xylar** [comment]
@akturner, I took the liberty of pushing to your branch.

@jonbob, I'm not quite sure why this worked as you expected in python 2.7, but it's easy to get the behavior you want.  The original author of this script, who you can look up if you like, was fond of putting in his own error catching that was less helpful than the error message you get when you don't put in error handling.  I have taken out those error messages and tested myself:
```
$ ./generate_e3sm_namelist_files.py -r Registry_processed.xml -d namelist_defaults.xml 
Traceback (most recent call last):
  File "/home/xylar/code/MPAS-Tools/generate_acme_namelist_files/minor_improvements/source_code_processing/e3sm_namelist_file_generator/./generate_e3sm_namelist_files.py", line 283, in <module>
    registry_tree = ET.parse(args.registry)
  File "/home/xylar/miniconda3/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/home/xylar/miniconda3/lib/python3.9/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: mismatched tag: line 105, column 3
```
I think the script should now behave the way you want.  Please update and retest.  If you're happy, I'll merge this PR before it languishes too much longer.

**Comment by xylar** [comment]
@jonbob, have you had a chance to retest this yet?

**Comment by jonbob** [comment]
Thanks @xylar - with your changes the script now picks up and points at the errors in the parsed file

**Review by jonbob — APPROVED** [review]
Tested and now works fine for me

**Comment by xylar** [comment]
Thanks @akturner and @jonbob!

**Pull request merged**
