### PR TITLE
Add ocean topography smoothing tool

### PR DESCRIPTION
**Pull request by xylar**
This tool will be used in Compass to smooth topography for EC and Icos30 meshes (perhaps others in the future).

### CODE REVIEW

**Comment by xylar** [comment]
@maltrud, I'm able to build the tool!  On to Compass.

**Comment by xylar** [comment]
## Testing

I used this to produce smoothed bathymetry and ice-shelf topography for the ECwISC and IcoswISC meshes in https://github.com/MPAS-Dev/compass/pull/733 and https://github.com/MPAS-Dev/compass/pull/734.

bottom_depth
ice_draft

**Review by maltrud — APPROVED** [review]
Looks good to me.  the guts of the algorithm that I used in my stand-alone code are replicated here, with extensions to handle ice shelf cavities.

**Comment by xylar** [comment]
Excellent, thank you, @maltrud!

**Pull request merged**
