### PR TITLE
Convert remaining landice-related tools to py3

### PR DESCRIPTION
**Pull request by matthewhoffman**
This merge converts the remaining landice tools to py3, as well as some additional shared tools that landice COMPASS uses.  It also adds a couple shared tools that landice COMPASS requires to the conda package.

### CODE REVIEW

**Comment by matthewhoffman** [comment]
@xylar , I tried testing my changes to the conda package but quickly ran into an error for which the internet was no help.
`conda build --python=3.7 recipe/meta.yaml`
yielded:
```
No handlers could be found for logger "libarchive"
Traceback (most recent call last):
  File "/Users/mhoffman/anaconda/bin/conda-build", line 7, in <module>
    from conda_build.cli.main_build import main
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 18, in <module>
    import conda_build.api as api
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import Config, get_or_merge_config, DEFAULT_PREFIX_LENGTH as _prefix_length
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/config.py", line 17, in <module>
    from .variants import get_default_variant
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/variants.py", line 15, in <module>
    from conda_build.utils import ensure_list, trim_empty_keys, get_logger
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 9, in <module>
    import libarchive
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/libarchive/ffi.py", line 184, in <module>
    c_int, check_int)
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/libarchive/ffi.py", line 95, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/Users/mhoffman/anaconda/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/Users/mhoffman/anaconda/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x1028b17b0, archive_read_open_filename_w): symbol not found
```

**Comment by xylar** [comment]
@matthewhoffman, I don't think this explains the problem, but you need to build the package from one directory up so it can see the full repo, not just the `conda_package` directory.

There's a problem right now I discussed with @jhkennedy where some packages on conda-forge support the latest hdf5 while others don't.  Because of this, `netcdf4` temporarily needs to be added to the `host` part of the `meta.haml`:
```
...
  host:
    - python
    - hdf5
    - libnetcdf
    - netcdf4
    - setuptools
...
```
This forces `hdf5` and `libnetcdf` to use versions of `hdf5` that are compatible with `netcdf4` when building the mesh conversion tools.  Again, this is not the problem that you saw but would be necessary if you want to get a test build working.

With this change, I was able to build the package just fine from this branch.

**Comment by xylar** [comment]
Regarding your error, if you want to work on it, I would do a clean install of Miniconda3 for OSX:
https://docs.conda.io/en/latest/miniconda.html

You can continue to use your anaconda for other things but I think your base environment must have some issues or something so at least for `conda-build` it may not be usable.

Then, activate the base environment:
```
source ~/miniconda3/etc/profile.d/conda.sh
conda activate
```
Install `conda-build` and try again from there.

**Comment by matthewhoffman** [comment]
@xylar , I updated my conda install and got that weird conda build error to go away, but I get a new error that appears related to the recipe and unrelated to my changes:
```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
WARNING: symlink_conda() is deprecated.
Collecting package metadata: ...working... done
Solving environment: ...working... done
Collecting package metadata: ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /Users/mhoffman/anaconda/conda-bld/work
  Test:
 /Users/mhoffman/anaconda/conda-bld/test_tmp
Leaving build/test environments:
  Test:
source activate  /Users/mhoffman/anaconda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
  Build:
source activate  /Users/mhoffman/anaconda/conda-bld/_build_env


Traceback (most recent call last):
  File "/Users/mhoffman/anaconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1397, in build
    create_build_envs(m, notest)
  File "/Users/mhoffman/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1281, in create_build_envs
    raise e
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: set(['geometric_features', 'pyevtk'])
```
Do you know how to debug this?

**Comment by xylar** [comment]
You haven't added the `conda-forge` channel, maybe?

```
conda config --add channels conda-forge 
```

**Comment by matthewhoffman** [comment]
@xylar , ok, that seemed to get me past that error, but now I got compiler error when trying to build the mesh_conversion_tools.  Will there be a chance to test the conda package in #261? Or is it important that I make sure everything works out of the package in this PR before I merge it?

**Comment by xylar** [comment]
@matthewhoffman, I'm sorry conda build is giving you so much trouble!  No, it's not necessary to iron out all the wrinkles here.  There will be a chance to make sure it builds in #261 and even after it is released if the problem is with the build recipe rather than the repo (there's a separate recipe in the "feedstock" on conda-forge).

I also tried the build myself from this branch and it worked fine under linux.  We have a working OSX build of the c++ tools on conda-forge already so I'm not worried about those working correctly.  I suspect the problem is something to do with your local conda build setup but I have no experience with conda build on OSX so I'm not going to be much help there, I'm afraid.

**Comment by matthewhoffman** [comment]
@xylar , ok thanks - I'll hold off on further trying to get the conda build process working on my laptop.  I've merged this, so you can proceed with #261 when ready.

**Pull request merged**
