### PR TITLE
Add mesh creation module to  mpas_tools conda package

### PR DESCRIPTION
**Pull request by xylar**
The major change in this merge is moving `jigsaw_to_MPAS` from [COMPASS](https://github.com/MPAS-Dev/MPAS-Model/tree/ocean/develop/testing_and_setup/compass/ocean/jigsaw_to_MPAS) to the `mpas_tools` conda package.  It is now in `mpas_tools.mesh.creation`.

Other changes in this PR include:
* Moving color map related functionality to the `viz` module
* Moving `mpas_tools.conversion` to `mpas_tools.mesh.conversion` (but `mpas_tools.conversion` still exists for backward compatibility
* Making entry points for relevant tools from `jigsaw_to_MPAS`
* Adding a bit of code to make sure `define_base_mesh.py` gets found in the current directory within the `build_mesh` module
* Update `mpas_tools` to v0.0.11 and `compass` metapackage to v0.1.9
* Add some tests to the recipe to make sure the new entry points and module are present
* Add some documentation of how developers should modify and test the `mpas_tools` package

`geometric_features` in `compass` has been updated to v0.1.11.

### CODE REVIEW

**Comment by xylar** [comment]
This PR is intended to be the first of two steps in addressing https://github.com/MPAS-Dev/MPAS-Model/issues/550.  The second step will be a follow-up PR to remove `jigsaw_to_MPAS` from COMPASS and to use these changes.

I have a `test_compass_0.1.6` environment on LANL IC that can be used to try this out.  However, I think that will be of limited use until the second PR is also posted, so stay tuned...

**Comment by xylar** [comment]
@dengwirda, hopefully these two new documents will help you get a sense of how to modify, build and test the conda package:
https://github.com/xylar/MPAS-Tools/blob/add_mesh_creation/conda_package/docs/making_changes.rst
https://github.com/xylar/MPAS-Tools/blob/add_mesh_creation/conda_package/docs/testing_changes.rst

If things are unclear, please make inline comments and I can clean these documents up.

**Comment by xylar** [comment]
@matthewhoffman, I think you are probably largely unaffected by this change but just wanted to make you aware.  Feel free to review or remove yourself, as you see fit.

**Comment by matthewhoffman** [comment]
@xylar , at the high level does this simply have the effect of changing which conda module would need to be loaded to have access to JIGSAW?

**Comment by xylar** [comment]
@matthewhoffman, for your purposes, the main changes would be:
* if you're using the mesh conversion wrappers within `mpas_tools`, the preferred way to access them is now via `mpas_tools.mesh.conversion` instead of `mpas_tools.conversion`
* when you install `mpas_tools` from conda-forge, it will soon have additional dependencies including `jigsaw` and `jigsawpy`.

So I guess the answer to your question is just that you would have access to `jigsaw` in a conda environment with `mpas_tools` even if you didn't explicitly ask for it.  But the changes don't otherwise relate to JIGSAW itself, just the tools that `ocean` uses in COMPASS to make JIGSAW meshes.

**Comment by xylar** [comment]
A added some more documentation to this PR. It may be that we decide to change the API enough that my docs for `build_mesh` aren't much use, but what's done is done...

**Comment by xylar** [comment]
@dengwirda and @matthewhoffman, do either of you want to review this?

If it is helpful, I have a test conda environment on Grizzly on LANL IC:
```
source /usr/projects/climate/SHARED_CLIMATE/anaconda_envs/base/etc/profile.d/conda.sh
conda activate test_compass_0.1.9
```

@mark-petersen and @sbrus89, please review this along with https://github.com/MPAS-Dev/MPAS-Model/pull/563

**Comment by xylar** [comment]
I bumped `geometric_features` in the next `compass` metapackage to 0.1.11.  The package hasn't been built yet so I'll need to test that before we do the final merge and release `mpas_tools`.

**Comment by xylar** [comment]
@mark-petersen and @sbrus89, neither of you officially approved this PR but you used a test build of this PR in your testing of https://github.com/MPAS-Dev/MPAS-Model/pull/563, which you did approve.  I'm going to reluctantly take that as a tacit approval of this PR in the interest of time but I would like to have your explicit approval in the future.

**Pull request merged**
