### PR TITLE
Added MPAS-Limited-Area

### PR DESCRIPTION
**Pull request by MiCurry**
This tool allows a user to specify a region using a variety of different
method, and then subsets a global MPAS-A grid.nc or static.nc file to be used
as a regional MPAS-A simulation.

### CODE REVIEW

**Comment by xylar** [comment]
@MiCurry and @mgduda, is this PR still in active development?

**Comment by MiCurry** [comment]
Hi @xylar, apologies about the late reply. Yes, we wouldd like to get this tool into MPAS-Tools, but it appears that we have forgotten about it.

@mgduda perhaps after the tutorial we can merge this in.

**Comment by mgduda** [comment]
@MiCurry What is meant in the PR description by "Where issues, and PR's should be made to it."? Is the intent that the MPAS-Limited-Area repository would still be used for Issue tracking and PRs after the code has been merged into the MPAS-Tools repository?

**Comment by MiCurry** [comment]
> @MiCurry What is meant in the PR description by "Where issues, and PR's should be made to it."? Is the intent that the MPAS-Limited-Area repository would still be used for Issue tracking and PRs after the code has been merged into the MPAS-Tools repository?

Yes, that is what I meant, but If you think we can manage it in this repository then I can remove that comment.

**Comment by mgduda** [comment]
> > @MiCurry What is meant in the PR description by "Where issues, and PR's should be made to it."? Is the intent that the MPAS-Limited-Area repository would still be used for Issue tracking and PRs after the code has been merged into the MPAS-Tools repository?
> 
> Yes, that is what I meant, but If you think we can manage it in this repository then I can remove that comment.

It seems like a lot less work to have a single repository for developing, maintaining, and distributing a code than to try tracking bugs in one repository but distributing the code from another. I'd advocate for merging the MPAS-Limited-Area tool into the MPAS-Tools repository, and then [archiving](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository/archiving-repositories) the MPAS-Limited-Area repository.

**Comment by MiCurry** [comment]
@mgduda I agree that does sound easier. I've removed the comment.

**Pull request closed without merging**
