### PR TITLE
Upgrade create_SCRIP_file_from_MPAS_mesh.py to python3

### PR DESCRIPTION
**Pull request by mark-petersen**
Simple upgrade to python 3. Just print parenthesis and spacing.

### CODE REVIEW

**Comment by mark-petersen** [comment]
Tested with e3sm-unified package on grizzly. It works.

**Comment by xylar** [comment]
@mark-petersen, could you run autopep8 on the script.  This will take out the spaces in your various `print ()` statements and may find some other issues.

Also, would it make sense to add this script to the conda package?  My guess is that it would, since we might want to use it in COMPASS.

**Comment by xylar** [comment]
I take that back, don't run autopep8.  I tried it and it changes too much.
Instead, could you just search and replace `print (` with `print(`?

**Comment by xylar** [comment]
@matthewhoffman, do you want to make `create_SCRIP_file_from_CISM_mesh.py` work with python 3 as part of this PR?

**Comment by xylar** [comment]
It looks like the conda package needs some attention so let me take care of adding the script to the package in a separate PR.

**Comment by mark-petersen** [comment]
@xylar thanks for looking at this. Funny, the space in `print ("` reveals that I think of print as a statement rather than a function. Old habits die hard. Lillian teases me that I use two spaces after a period when typing, which reveals that I am an "old person".

**Comment by xylar** [comment]
> Funny, the space in print (" reveals that I think of print as a statement rather than a function. 

That's precisely what changed from python 2.7 to 3: `print` became a function and that's why you now need the parentheses.

> Lillian teases me that I use two spaces after a period when typing, which reveals that I am an "old person".

I do that, too.  I learned to type properly on a typewriter in high school.  I'll never be able to break the habit now.  Hopefully the current generation of postdocs are young enough to not have picked up that habit.

**Comment by xylar** [comment]
@mark-petersen, your call if you want to wait on @matthewhoffman to see if he wants to fix the CISM script or if we just let this be.

**Comment by mark-petersen** [comment]
Merging. @matthewhoffman feel free to alter the land ice script when you see fit.

**Comment by xylar** [comment]
@mark-petersen, please include the PR number in your merge commit.  It helps a lot with drafting a release.  The easiest way to do that is to just use the merge button here on GitHub.

**Comment by mark-petersen** [comment]
OK, good to know. I never use the button on the main repo because I always merge locally and test again. Do you want me to change the text on the merge commit and do a force push?

**Comment by xylar** [comment]
@mark-petersen, no, I don't think we should *ever* do a force push to master.  Plus, I've already done the release.

I really think the merge button is quite safe.  I understand that it's the policy not to use it on the MPAS-Model repo (though I think that's unnecessarily cautious) but I have never had problems with it.  It always does a merge commit rather than a fast-forward, as we would want.  My understanding was that was always the concern with MPAS-Model.

**Pull request merged**
