### PR TITLE
Move functions for adding depth coordinates to MPAS-Ocean into the conda pacakge

### PR DESCRIPTION
**Pull request by xylar**
The functions for adding ocean depth coord, along with entry points, are now in the conda package directly.  Docstrings have been updated.

The old `ocean/add_depth_coord directory` outside the conda package has been removed.

The documentation has been updated to include the main accessor functions as well as `compute_depth` and `compute_zmid`.

closes #361

### CODE REVIEW

**Comment by xylar** [comment]
@sterlingbaldwin, could you see if this addresses what you wanted to accomplish in https://github.com/MPAS-Dev/MPAS-Tools/pull/361?

**Comment by xylar** [comment]
@sterlingbaldwin, let me know if you're okay with this.  If so, I'll merge as soon as I verify that the docs look okay.

**Comment by xylar** [comment]
@sterlingbaldwin, I'm going to go ahead and merge. I think this should do what you want.

**Comment by sterlingbaldwin** [comment]
Sorry @xylar just saw this now. Need to check my github notifications more. This does exactly what I needed, thanks!

**Pull request merged**
