### PR TITLE
Create a `landice` module for the `mpas_tools` conda package

### PR DESCRIPTION
**Pull request by trhille**
Create a `landice` module for the `mpas_tools` conda package, and add a `visualization` submodule containing `plot_transect()`, `plot_map()`, `plot_grounding_lines()`, and various helper functions.

Note: Currently these tools are designed for fields defined on cells. Plotting fields on edges will require some changes.

Documentation can be found here: https://portal.nersc.gov/cfs/fanssie/trhille/mpas-tools-docs-landice_module/

### CODE REVIEW

**Comment by xylar** [comment]
Exciting!  You also need to add an empty `__init__.py` in the `landice` directory so that directory gets recognized as part of the `mpas_tools` package.

**Comment by trhille** [comment]
Testing
-------
Creating a map of `bedTopography` with the grounding line contoured in white:
image

Adding grounding lines from multiple files to a map of `bedTopography`:
image

Creating maps of `surfaceSpeed` on a log scale, with grounding lines contoured in white:
image

Transects down Thwaites Glacier from ISMIP6 expAE02 at 2200-2204 (I still need to work out coloring by time when using multiple input files for this one):
image

Transects of geometry and temperature down Thwaites Glacier from ISMIP6 expAE02 at 2015, 2100, 2200, and 2300:
image

**Comment by trhille** [comment]
@xylar and @andrewdnolan, will either of you be able to review this soon?

**Comment by xylar** [comment]
@trhille, could you also add some documentation to https://github.com/MPAS-Dev/MPAS-Tools/tree/master/conda_package/docs and make sure it builds locally?

https://mpas-dev.github.io/MPAS-Tools/stable/building_docs.html

**Comment by trhille** [comment]
@xylar, I've added and build the documentation. Everything looks as expected.

**Review by xylar — APPROVED** [review]

**Comment by xylar** [comment]
@trhille, this looks good to me.  @andrewdnolan, I'll count on you testing this to make sure it works for you.

**Comment by xylar** [comment]
@andrewdnolan and @trhille, how is this coming along?  I need to make a new MPAS-Tools release that includes #571 pretty soon.  It would also be nice to have #567 in a release (since I promised to do that almost 2 months ago).

**Comment by andrewdnolan** [comment]
Sorry about the delay with this! I will do some testing first thing on Monday morning and report back!

**Comment by andrewdnolan** [comment]
# Testing 
@trhille Sorry this look so long to review, but it's looking great! I've tested this on `perlmutter` with output from `Exp05` from ISMIP6 Greenland and everything seems to work as expected. 

### `plotmap` / `plot_grounding_lines`: 

Screenshot 2024-07-01 at 1 53 53 PM

P.S. I also tested plotting the grounding line directly from `plotmap` with the `plot_grounding_line` kwarg, which worked for me aswell. 

### Custom field for `plotmap`:

Screenshot 2024-07-01 at 1 57 00 PM

### `plot_transect`

I will admit I had limited success with line plots for transect from multiple files, but I don't think that should hold up the PR. 

image

__But__, the transect of 3D field worked great for me! 

Screenshot 2024-07-01 at 2 00 59 PM

**Review by andrewdnolan — APPROVED** [review]

**Comment by xylar** [comment]
Nice @trhille!  Thanks for the review, @andrewdnolan!

**Pull request merged**
