### PR TITLE
Add scripts for adding depth or zMid to MPAS-O data, or computing zMid on its own

### PR DESCRIPTION
**Pull request by xylar**
When `zMid` is added to a file, it is computed from `bottomDepth`, `maxLevelCell` and `layerThickness` from an initial condition or restart file that may be different from the input file to which `zMid` will be added.

When a time-varying `zMid` is computed, it used the time-varying `layerThickness` from the input file, not from the initial condition file.

`depth` is a 1D reference depth computed from `refBottomDepth` and does not account for either time variability or non-z-level horizontal variability.

### CODE REVIEW

**Comment by xylar** [comment]
## Usage

First, you'll need a compatible python environment.  Here's what I did:
```
conda create -y -n process_mpaso python=3.6 numpy netcdf4 xarray
conda activate process_mpaso
```

Then, just run the script with something like:
```
./add_depth_coord.py -c mpaso.rst.0001-05-01_00000.nc -i mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc -o mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01_zMid.nc
```
The `-c` flag points to the "coordinate" file (an initial condition or restart file), `-i` points to the input file to which `zMid` should be added and `-o` points to the output file, which should be virtually identical to the input file except that `zMid` is added and the `history` attribute has the command appended.

**Comment by xylar** [comment]
@czender, @maltrud asked me if I could put a script together to construct the local vertical coordinate (at cell centers) in MPAS-Ocean output files.  He indicated this was something you would need for post-processing MPAS-Ocean output for ESFG.  This pull request is my attempt to address that need.  I'm very much open to suggestions for how I can change the script to make it better fit your needs.

Please give it a try and let me know at your convenience what modifications (if any) are needed.  Feel free to approve the pull request as soon as you're happy with it.

**Comment by xylar** [comment]
@maltrud, I'm including you as a reviewer partly just to keep you in the loop.  I know that Python isn't really your thing but if you want to take a look at the code at least from a high level and make sure you don't have concerns, that would be great.

**Comment by xylar** [comment]
@czender, this script needs to be run before regridding because maxLevelCell is not meaningful after regridding.  My expectation was that you would run this script first and then regrid the result, meaning you could take care of CF-compliance as at that point.

Nevertheless, I believe it's a one-line change to make zMid a coordinate in xarray so I'll take care of that right away.

**Comment by xylar** [comment]
Okay, it was more like 10 lines rather than 1, but I've added `zMid` as a coordinate for all variables with `nCells` and `nVertLevels` s dimensions.

@czender, note that zMid varies (albeit only slightly for output without sub-ice-shelf cavities) as a function of horizontal location.  @maltrud and I had discussed that it might be desirable to regrid to a coordinate with spatially invariant z (or ignore the spatial variation in zMid in z-tilde meshes without ice-shelf cavities).  I haven't attempted to take care of that here, so it's something we should perhaps discuss.

**Comment by xylar** [comment]
@maltrud, please let me know your thoughts.

> Would you like it if this script were applied to the data to be regridded for CMIP6? 

I believe that was the intention.  That the CMIP6 data is not very useful without the vertical coordinate included.

@sterlingbaldwin, perhaps you are the best person to talk to about the feasibility of that?  Is there a way for you to run this script on each MPAS data file to add `zMid` before doing other processing?

**Comment by czender** [comment]
FYI the MPAS 3D field timeseries for CMIP6 takes about 2hr per each 25 year segment, vs. only 15min for each atmosphere 3D field timeseries. Much of the reason for this disparity is pre-processing MPAS data (adding _FillValue, permuting dimension order, demoting precision) that EAM does not require. I'm all in favor of adding 1D zmid-like coordinates to CMIP6 3D timeseries, but a 3D zmid is almost untenable, because it would double the size of each timeseries file. So I urge the MPAS folks to consider creating the approximate 1D zmid coordinate that Xylar mentioned, and then we would automatically include that with 3D timeseries. Separately we would take the full 3d zmid variable (named something else so as not to conflict with the 1D zmid) and create its own 3d timeseries. Then users who are OK with the approximate version can use 1D zmid, and power used can download the full 3D zmid separately. Thoughts?

**Comment by xylar** [comment]
@czender, that sounds reasonable to me.  Adding `refZMid` (this is the internal MPAS-Ocean name and could be whatever you like), the original z-level vertical coordinate, would be easy.  Producing a time series of zMid (3D) for CMIP6 separate from other variables would also be reasonable.  It might not be used by very many people.  Still, I think it would serve to clarify that refZMid is only an approximate vertical coordinate.

@sterlingbaldwin, what can I do to turn this into a script that is useful to you?

**Comment by xylar** [comment]
Okay, I've created a script `add_refZMid.py` that could be used to add this 1D coordinate to an MPAS-Ocean file.  Again, I'm happy to rename it but I'm hesitant to call it `zMid` because that it the name of the 3D coordinate in MPAS-Ocean internally.

@sterlingbaldwin and @czender, please do let me know if this is useful to you.

I've moved the other script to `add_zMid.py` to keep things at least relatively clear.  It doesn't sound like that script will be useful for CMIP6, but I'll think about a good way to compute `zMid` as a function of time in case we decide to use that.

**Comment by xylar** [comment]
One more update: I added `write_time_varying_zMid.py` to compute a time series of the 3D vertical coordinate, as @czender discusses above.  The usage would be something like:
```
./write_time_varying_zMid.py -c mpaso.rst.0001-05-01_00000.nc -i mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc -o mpaso.zMid.0001-01-01.nc -p timeMonthly_avg_
```

**Comment by czender** [comment]
This is good progress. One way for this to make it into the CMIP6 files would be to run it on every ocean file that will be processed by the splitter before the splitter runs. If the CF-compliance of refzMid was handled correctly then, then NCO should extract refzMid into every timeseries file with a 3D variable and no others. What do MPAS folks think of the coordinate name "depth" rather than "refzMid"? The former seems clearer to me. @sterlingbaldwin is it possible to run this script on all the ocean files first?

**Comment by sterlingbaldwin** [comment]
Hey @xylar thanks for tagging me in this. This script needs to be added before running the (currently non-existent) ocean CMOR conversion scripts right? I think it would be fairly straightforward to add a call to this script as a setup step before running the CMOR handlers.

**Comment by xylar** [comment]
@sterlingbaldwin, yes, that sounds exactly right.  Specifically, `ocean/add_depth_coord/add_depth.py` would need to run.  If you're running your scripts from a place where `e3sm-unified` is available, you should have all the python packages you need.  If not, I think you'll just need `numpy`, `xarray` and `netcdf4`, as I mention above.

I'll leave this pull request open until you've had a chance to try out the script on some data but it could be good to merge it to `master` before you finalize the workflow.  I imagine you'll just want to download the script with wget rather than messing with cloning the tools repo or anything like that.

**Comment by czender** [comment]
It ideally should be run before ncclimo.

**Comment by xylar** [comment]
@czender, that might end up being impractical given how many files are involved before vs. after ncclimo but I'll leave it up to @sterlingbaldwin to say what is doable and what isn't.

**Comment by czender** [comment]
Agreed. At this point let Sterling do whatever is easiest so he can get started...

**Comment by maltrud** [comment]
does ncclimo get run before or after remapping?

**Comment by maltrud** [comment]
perfect, @czender , thanks for clarifying. my main requirement here is that the regridding be done _after_ redefining the vertical coordinate using @xylar 's new script.

also (referring back to an earlier thread here) i don't see any compelling reason to include time-varying refZmid, even in its own file.  if someone really cares, they can figure out how to generate it using layer thicknesses.

**Comment by xylar** [comment]
>  i don't see any compelling reason to include time-varying refZmid, even in its own file. if someone really cares, they can figure out how to generate it using layer thicknesses.

I'm fine with not including zMid(t) but:
* I am skeptical if you have the data to compute this after remapping (in addition to `layerThickness`, you would need `bottomDepth` and you would need `layerThickness` to be zero below `maxLevelCell` as opposed to being masked out)
* As soon as we have simulations with the ALE coordinate (e.g. those with ice-shelf cavities), the 1D `depth` coordinate is no longer meaningful everywhere, so we should have a way to handle this down the road

**Comment by maltrud** [comment]
@xylar i totally agree with your comments.  i would say if anyone actually needs zMid(t) they should be doing their analysis on the native grid.  and when it comes time to deal with the ALE grid, we're going to have to rethink the whole shebang, so i don't have any problem ignoring it for now.

**Comment by maltrud** [comment]
@xylar , i finally gave this a test--thanks for doing it so quickly.  as usual, i wasn't clear enough about what i envisioned.  i wanted a coordinate transformation from depth index to depth value, so instead of:

double timeMonthly_avg_velocityZonal(Time, nCells, nVertLevels) ;
we'd have instead:
double timeMonthly_avg_velocityZonal(Time, nCells, depth) ;

so we'd have something more like POP (of course) where z_t <=> depth and nVertLevels disappears just like km does in POP:

float UVEL(time, z_t, nlat, nlon) ;

but is this what we really want?  i know IOMB wants files with a true depth coordinate, but maybe we don't want to do this for CMIP?

**Comment by xylar** [comment]
@maltrud, okay, that's easy enough to change.  So just rename `nVertLevels` to `depth` in addition to adding the `depth` coordinate in `add_depth.py`, right?  (I'll do the same in the other two scripts, though they're no longer the focus of the current effort.)

**Comment by xylar** [comment]
@maltrud, please make sure the latest commit takes care of your concern.  My test show that `nVertLevels` has, indeed, been renamed as `depth`.

Also, I want to make sure we want the positive down `depth` that is currently in there.  It would be simple enough to add a minus sign now to make it positive up...

**Comment by xylar** [comment]
@sterlingbaldwin, let me know when you get a chance to test this.

**Comment by maltrud** [comment]
@xylar , i think we're getting close.  this seems to work fine--and ferret interprets depth as positive down.  the problem now is that ncremap fails.  @czender , does the -P mpas option in ncremap key off of nVertLevels?  if yes, maybe we should rename (again, sorry Xylar) to nVertDepths or something so ncremap can key off of either one, which should still be unique to mpas.

**Comment by czender** [comment]
@maltrud, yes I think that `ncremap` needs to be told where to place the new `depth` dimension when it permutes the dimension order of the input fields prior to applying regridding weights. Can you please put a file, before and after processing by `add_depth.py`, for me to test on edison? I'll make the changes to the `ncremap` in `~zender/bin_edison` on edison so you can test it. Monday latest. I think the dimension name should stay as `depth` so that it is a coordinate variable.

**Comment by maltrud** [comment]
thanks, @czender .  files are in /global/project/projectdirs/acme/maltrud/forCharlie

**Comment by czender** [comment]
@maltrud @xylar 
As of version 4.7.9-alpha03 (installed in `~zender/bin_edison`),
`ncremap -P mpas` works fine with `depth`.
These attributes changes/additions to `depth` will improve its
CF-compliance, so please consider implementing them in `add_depth.py`
prior to using for CMIP6:
```
       depth:units = "meters" ; # CF convention is plural "units" not "unit"
       depth:positive = "down" ; # CF convention
       depth:standard_name = "depth" ; # CF convention

```
The same attributes could/should be added to `zMid` too.

**Comment by xylar** [comment]
@czender, thanks very much for this helpful feedback.

Just to be clear, the `standard_name` for `zMid` should also be `"depth"`?

I'll add a commit with these changes in a few minutes.

**Comment by czender** [comment]
Yes, in my opinion. It and `depth` describe the same physical quantity, albeit at different levels of approximation.

**Comment by xylar** [comment]
Okay, great!  I thought so too but wanted to be sure.

**Comment by xylar** [comment]
Thanks for catching `unit` --> `units`.  I think that was a typo.  The other CF-compliance issues are things I need to become more familiar with but haven't really had the time so far.  I really appreciate you nudging us in the right direction.

**Comment by xylar** [comment]
@maltrud, can you run the script again (to make sure I didn't break anything and so @czender has updted files)?

**Comment by maltrud** [comment]
@xylar and @czender , both the updated script and ncremap are working for me.  thanks so much for doing this!

**Comment by czender** [comment]
@xylar 
I have not seen an example file with `zMid` in it so I'm struggling to understand this:

`ds.zMid.attrs['positive'] = 'up'`

If `zMid` is truly a depth coordinate (like `depth`), then I think it should have the same `positive` convention (i.e., `down`). If `zMid` has the opposite sign convention to `depth`, and so is always negative, then I think we should not give it a `standard_name` of `depth`. Instead just don't store a `standard_name` for `zMid`. Here is the CF definition of `depth`:

> Depth is the vertical distance below the surface.

**Comment by xylar** [comment]
@czender, `zMid` is positive up so I have removed the `standard_name` attribute.

**Comment by czender** [comment]
@xylar I understand what `zMid` is now. Originally I thought it was just a 3D version of `depth`.  BTW, I promised in my latest Statement of Work (SOW) to help improve the CF-compliance of MPAS output so I am glad to hear this interests you too. Can you help me by pointing me to where in the MPAS source code the attributes (e.g., `long_name`, `units`) to some standard variables (e.g., `temperature`) either should be defined (e.g., for raw history files) or are defined (e.g., for AMs like `timeSeriesStatsMonthly`)?

**Comment by czender** [comment]
@xylar @sterlingbaldwin @maltrud Not necessarily for CMIP6 but in the longer run it might make sense for `ncremap` to have an option to run `add_depth.py`. Yet I can foresee silly people misusing that option by running it on files with only 2D variables. This could be averted by modifying `add_depth.py` to do nothing (exit without changing anything) if it finds in a quick pre-check that the input file has no 3D variables. And then `ncremap` could just call `add_depth.py` whenever `-P mpas` is invoked and an MPAS "coordinate" file (same as `-c` argument to `add_depth.py`) is provided with, e.g., `--mpas_depth=filename`. Thoughts?

**Comment by xylar** [comment]
@czender, I think yours is a good idea.  I just added an if statement to handle your request.

One consideration is that `add_depth.py` depends on the `xarray` package, which isn't otherwise a dependency of `nco`.  So we'll want to think about that a little bit.  On conda-forge, maybe easiest to just add xarray as a dependency.  Elsewhere, that may not be a good idea.

**Comment by czender** [comment]
Thanks for making this change. I'm also concerned about dependency proliferation. `add_depth.py` is only for MPAS files and I want NCO to be lightweight and not depend on the entire Python ecosystem. I think it would suffice for NCO to note the dependence on Python/xarray etc in the error output printed if the `add_depth.py` command fails. 

This would improve CF-compliance: Please prepend a time-stamp (preferably though not necessarily formatted like UNIX `date` output) to `add_depth.py` (and brethren) history attribute annotation so output file contains, e.g.,
`history = "Thu Jan  3 10:58:37 2019: ./add_depth_coord.py -i u.nc -o u_add_depth.nc -c oEC60to30v3_60layer.170905.nc\n"
`

**Comment by czender** [comment]
Another way to polish CF-compliance of `add_depth.py` is prevent it adding `_FillValue` to `depth` because 1) `depth` has valid values at each level 2) `depth` is a coordinate variable and it is bad form for coordinates to have missing values or the `_FillValue` attribute. `zMid` can though need not have `_FillValue` depending on whether folks might wish to use it as a mask for bathymetry.

**Comment by xylar** [comment]
Update: After playing around a little bit with xarray options, I was able to use the `mask_and_scale=False` option to `open_dataset` to preserve `_FillValue` attributes.  Corresponding changes were needed to use this attribute when writing out to a file.  `depth` now has no `_FillValue` attribute but `zMid` has one with the standard NetCDF4 fill value.

**Comment by czender** [comment]
FYI @xylar @sterlingbaldwin @maltrud  the latest snapshot of `ncremap` supports `add_depth.py`. Invoke ncremap with `--dpt` for a file that has all the info in it, or invoke with `--mpas_fl=filename` to supply a file with the `refBottomDepth` coordinate. `--dpt_fl` is a synonym. Not documented yet. If you have a chance to try, let me know what you think. Here's an example invocation:

`ncremap -P mpas --dpt_fl=${DATA}/hdf/mpas_refBottomDepth_60lyr.nc -m ${DATA}/maps/map_oEC60to30v3_to_cmip6_180x360_aave.20181001.nc ${DATA}/hdf/mpaso.lrz.hist.am.timeSeriesStatsMonthly.0001-12-01.nc ~/foo.nc`

**Comment by xylar** [comment]
@czender, I added `depth_bnds` and the valid max/min as you requested.  I also changed the order of attributes as you suggested.  Please let me know if this output looks right:

```
$ ncdump -h mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01_depth.nc
netcdf mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01_depth {
dimensions:
	nMerHeatTransBinsP1 = 181 ;
	Time = 1 ;
	string64 = 64 ;
	nCells = 236358 ;
	depth = 100 ;
	nEdges = 718179 ;
	nVertLevelsP1 = 101 ;
	nOceanRegions = 7 ;
	nOceanRegionsTmp = 7 ;
	nbnd = 2 ;
variables:
...
	double depth(depth) ;
		depth:long_name = "reference depth of the center of each vertical level" ;
		depth:standard_name = "depth" ;
		depth:units = "meters" ;
		depth:positive = "down" ;
		depth:valid_min = 0. ;
		depth:valid_max = 5999.85620570183 ;
		depth:bounds = "depth_bnds" ;
	double depth_bnds(depth, nbnd) ;
		depth_bnds:long_name = "Gridcell depth interfaces" ;

// global attributes:
		:on_a_sphere = "YES" ;
...
		:file_id = "gtedsbi3oh" ;
		:coordinates = "depth_bnds" ;
data:

 depth = 0.754999995231628, 2.32249999046326, 4.00850009918213, 
    5.82149982452393, 7.77049970626831, 9.86400032043457, 12.111499786377, 
    14.5234994888306, 17.111499786377, 19.886999130249, 22.861499786377, 
    26.0480003356934, 29.4600009918213, 33.111499786377, 37.0180015563965, 
    41.1955032348633, 45.6605033874512, 50.4305038452148, 55.5240020751953, 
    60.9605026245117, 66.7605056762695, 72.9455032348633, 79.5380020141602, 
    86.5615005493164, 94.0404968261719, 102.000495910645, 110.468994140625, 
    119.474494934082, 129.045989990234, 139.216995239258, 150.016998291016, 
    161.477005004883, 173.637008666992, 186.532012939453, 200.197021484375, 
    214.672027587891, 230.002029418945, 246.232025146484, 263.402038574219, 
    281.557037353516, 300.747039794922, 321.017028808594, 342.417022705078, 
    365.007019042969, 388.842010498047, 413.977020263672, 440.467010498047, 
    468.372009277344, 497.757019042969, 528.682006835938, 561.212036132812, 
    595.417053222656, 631.367065429688, 669.137084960938, 708.797058105469, 
    750.417053222656, 794.077026367188, 839.857055664062, 887.837036132812, 
    938.10205078125, 990.732055664062, 1045.81201171875, 1103.43200683594, 
    1163.67700195312, 1226.63696289062, 1292.40197753906, 1361.06201171875, 
    1432.71203613281, 1507.45202636719, 1585.37707519531, 1666.58203125, 
    1751.1669921875, 1839.22705078125, 1930.86206054688, 2026.17211914062, 
    2125.25708007812, 2228.20703125, 2335.15698242188, 2446.20703125, 
    2561.40698242188, 2680.85693359375, 2804.70703125, 2933.05712890625, 
    3065.95703125, 3203.55712890625, 3345.95703125, 3493.20703125, 
    3645.40698242188, 3802.65698242188, 3965.05688476562, 4132.65673828125, 
    4305.556640625, 4483.8564453125, 4667.6064453125, 4856.90625, 
    5051.8564453125, 5252.50634765625, 5458.90625, 5671.15625, 
    5889.30615234375 ;

 depth_bnds =
  0, 1.50999999046326,
  1.50999999046326, 3.13499999046326,
  3.13499999046326, 4.882000207901,
  4.882000207901, 6.76099944114685,
  6.76099944114685, 8.77999997138977,
  8.77999997138977, 10.9480006694794,
  10.9480006694794, 13.2749989032745,
  13.2749989032745, 15.7720000743866,
  15.7720000743866, 18.4509994983673,
  18.4509994983673, 21.3229987621307,
  21.3229987621307, 24.4000008106232,
  24.4000008106232, 27.6959998607635,
  27.6959998607635, 31.224002122879,
  31.224002122879, 34.9989974498749,
  34.9989974498749, 39.0370056629181,
  39.0370056629181, 43.3540008068085,
  43.3540008068085, 47.9670059680939,
  47.9670059680939, 52.8940017223358,
  52.8940017223358, 58.1540024280548,
  58.1540024280548, 63.7670028209686,
  63.7670028209686, 69.7540085315704,
  69.7540085315704, 76.1369979381561,
  76.1369979381561, 82.9390060901642,
  82.9390060901642, 90.1839950084686,
  90.1839950084686, 97.8969986438751,
  97.8969986438751, 106.103993177414,
  106.103993177414, 114.833995103836,
  114.833995103836, 124.114994764328,
  124.114994764328, 133.976985216141,
  133.976985216141, 144.457005262375,
  144.457005262375, 155.576991319656,
  155.576991319656, 167.377018690109,
  167.377018690109, 179.896998643875,
  179.896998643875, 193.167027235031,
  193.167027235031, 207.227015733719,
  207.227015733719, 222.117039442062,
  222.117039442062, 237.887019395828,
  237.887019395828, 254.577030897141,
  254.577030897141, 272.227046251297,
  272.227046251297, 290.887028455734,
  290.887028455734, 310.607051134109,
  310.607051134109, 331.427006483078,
  331.427006483078, 353.407038927078,
  353.407038927078, 376.606999158859,
  376.606999158859, 401.077021837234,
  401.077021837234, 426.877018690109,
  426.877018690109, 454.057002305984,
  454.057002305984, 482.687016248703,
  482.687016248703, 512.827021837234,
  512.827021837234, 544.536991834641,
  544.536991834641, 577.887080430984,
  577.887080430984, 612.947026014328,
  612.947026014328, 649.787104845047,
  649.787104845047, 688.487065076828,
  688.487065076828, 729.107051134109,
  729.107051134109, 771.727055311203,
  771.727055311203, 816.426997423172,
  816.426997423172, 863.287113904953,
  863.287113904953, 912.386958360672,
  912.386958360672, 963.817143201828,
  963.817143201828, 1017.6469681263,
  1017.6469681263, 1073.9770553112,
  1073.9770553112, 1132.88695836067,
  1132.88695836067, 1194.46704554558,
  1194.46704554558, 1258.80688023567,
  1258.80688023567, 1325.99707484245,
  1325.99707484245, 1396.12694859505,
  1396.12694859505, 1469.29712367058,
  1469.29712367058, 1545.6069290638,
  1545.6069290638, 1625.14722132683,
  1625.14722132683, 1708.01684117317,
  1708.01684117317, 1794.31714320183,
  1794.31714320183, 1884.13695836067,
  1884.13695836067, 1977.58716273308,
  1977.58716273308, 2074.75707554817,
  2074.75707554817, 2175.75708460808,
  2175.75708460808, 2280.65697789192,
  2280.65697789192, 2389.65698695183,
  2389.65698695183, 2502.75707554817,
  2502.75707554817, 2620.05688929558,
  2620.05688929558, 2741.65697789192,
  2741.65697789192, 2867.75708460808,
  2867.75708460808, 2998.35717320442,
  2998.35717320442, 3133.55688929558,
  3133.55688929558, 3273.55736851692,
  3273.55736851692, 3418.35669398308,
  3418.35669398308, 3568.05736851692,
  3568.05736851692, 3722.75659632683,
  3722.75659632683, 3882.55736851692,
  3882.55736851692, 4047.55640101433,
  4047.55640101433, 4217.75707554817,
  4217.75707554817, 4393.35620570183,
  4393.35620570183, 4574.35668492317,
  4574.35668492317, 4760.85620570183,
  4760.85620570183, 4952.95629429817,
  4952.95629429817, 5150.75659632683,
  5150.75659632683, 5354.25609898567,
  5354.25609898567, 5563.55640101433,
  5563.55640101433, 5778.75609898567,
  5778.75609898567, 5999.85620570183 ;
}
```

I'll also be happy to test your latest `ncremap` as soon as I have a chance.

**Comment by xylar** [comment]
@czender, I was, indeed, able to use your latest `ncremap` (a copy of which I downloaded into my local directory) as follows:
```
export PATH=~/Desktop/test_zMid:$PATH
./ncremap -P mpas --dpt_fl=mpaso.rst.0001-05-01_00000.nc -m map_oEC60to30v3wLI_to_0.5x0.5degree_bilinear.nc -v timeMonthly_avg_layerThickness mpaso.hist.am.timeSeriesStatsMonthly.0001-01-01.nc test_layerThickness.nc
```

The results look like so:
```
$ ncdump -h test_layerThickness.nc | more
netcdf test_layerThickness {
dimensions:
	lat = 360 ;
	lon = 720 ;
	nbnd = 2 ;
	depth = 100 ;
	Time = 1 ;
variables:
	double lat(lat) ;
		lat:long_name = "Latitude" ;
		lat:standard_name = "latitude" ;
		lat:units = "degrees_north" ;
		lat:axis = "Y" ;
		lat:valid_min = -90. ;
		lat:valid_max = 90. ;
		lat:bounds = "lat_bnds" ;
	double lon(lon) ;
		lon:long_name = "Longitude" ;
		lon:standard_name = "longitude" ;
		lon:units = "degrees_east" ;
		lon:axis = "X" ;
		lon:valid_min = -180. ;
		lon:valid_max = 180. ;
		lon:bounds = "lon_bnds" ;
	double lat_bnds(lat, nbnd) ;
		lat_bnds:long_name = "Gridcell latitude interfaces" ;
	double lon_bnds(lon, nbnd) ;
		lon_bnds:long_name = "Gridcell longitude interfaces" ;
	double gw(lat) ;
		gw:long_name = "Latitude quadrature weights (normalized to sum t
o 2.0 on global grids)" ;
	double area(lat, lon) ;
		area:long_name = "Solid angle subtended by gridcell" ;
		area:standard_name = "area" ;
		area:units = "steradian" ;
		area:cell_methods = "lat, lon: sum" ;
	double depth(depth) ;
		depth:long_name = "reference depth of the center of each vertica
l level" ;
		depth:standard_name = "depth" ;
		depth:units = "meters" ;
		depth:positive = "down" ;
		depth:valid_min = 0. ;
		depth:valid_max = 5999.85620570183 ;
		depth:bounds = "depth_bnds" ;
		depth:_FillValue = -9.99999979021477e+33 ;
	double depth_bnds(depth, nbnd) ;
		depth_bnds:long_name = "Gridcell depth interfaces" ;
		depth_bnds:_FillValue = -9.99999979021477e+33 ;
	double timeMonthly_avg_layerThickness(Time, depth, lat, lon) ;
		timeMonthly_avg_layerThickness:units = "m" ;
		timeMonthly_avg_layerThickness:long_name = "layer thickness" ;
		timeMonthly_avg_layerThickness:_FillValue = -9.99999979021477e+3
3 ;
		timeMonthly_avg_layerThickness:cell_measures = "area: area" ;
...
```

**Comment by xylar** [comment]
Note that NCO is adding `_FillValue`s to `depth` and `depth_bnds`, although we ideally didn't want them.  I think that's an inevitable side effect of MPAS's poor treatment of `_FillValue`.

**Comment by xylar** [comment]
Done.

**Comment by xylar** [comment]
@maltrud, could you take a look at these scripts and approve them by inspection if you're happy to do that?  We can always fix any bugs that come up later but they're the basis for what we're doing in https://github.com/E3SM-Project/e3sm_to_cmip/ already so they might as well go in.

**Pull request merged**
